# Generated by Django 5.2.9 on 2026-01-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallary', 'verbose_name_plural': 'product gallary'},
        ),
    ]
